server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: app-ci-cd
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  datasource:
    url: jdbc:mysql://localhost:3306/db_name
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql


broker:
  name:
    key: logs
    exchange: ex_logstash